export const employees = [
    {
      id: "NV001",
      name: "Nguyễn Văn An",
      phone: "0901234567",
      email: "an.nguyen@gmail.com",
      role: "Admin",
    },
    {
      id: "NV002",
      name: "Trần Thị Bình",
      phone: "0912345678",
      email: "binh.tran@gmail.com",
      role: "Manager",
    },
    {
      id: "NV003",
      name: "Lê Minh Cường",
      phone: "0923456789",
      email: "cuong.le@gmail.com",
      role: "Staff",
    },
    {
      id: "NV004",
      name: "Phạm Quốc Đạt",
      phone: "0934567890",
      email: "dat.pham@gmail.com",
      role: "Staff",
    },
    {
      id: "NV005",
      name: "Hoàng Gia Hân",
      phone: "0945678901",
      email: "han.hoang@gmail.com",
      role: "Manager",
    },
    {
      id: "NV006",
      name: "Đỗ Thành Long",
      phone: "0956789012",
      email: "long.do@gmail.com",
      role: "Staff",
    },
    {
      id: "NV007",
      name: "Vũ Khánh Linh",
      phone: "0967890123",
      email: "linh.vu@gmail.com",
      role: "Staff",
    },
    {
      id: "NV008",
      name: "Bùi Đức Mạnh",
      phone: "0978901234",
      email: "manh.bui@gmail.com",
      role: "Admin",
    },
    {
      id: "NV009",
      name: "Ngô Thị Mai",
      phone: "0989012345",
      email: "mai.ngo@gmail.com",
      role: "Staff",
    },
    {
      id: "NV010",
      name: "Phan Tuấn Kiệt",
      phone: "0990123456",
      email: "kiet.phan@gmail.com",
      role: "Manager",
    },
    {
      id: "NV011",
      name: "Đặng Hải Nam",
      phone: "0901112233",
      email: "nam.dang@gmail.com",
      role: "Staff",
    },
    {
      id: "NV012",
      name: "Lý Thanh Tâm",
      phone: "0912223344",
      email: "tam.ly@gmail.com",
      role: "Staff",
    },
    {
      id: "NV013",
      name: "Tạ Nhật Minh",
      phone: "0923334455",
      email: "minh.ta@gmail.com",
      role: "Admin",
    },
    {
      id: "NV014",
      name: "Trương Bảo Ngọc",
      phone: "0934445566",
      email: "ngoc.truong@gmail.com",
      role: "Manager",
    },
    {
      id: "NV015",
      name: "Nguyễn Hoài Phương",
      phone: "0945556677",
      email: "phuong.nguyen@gmail.com",
      role: "Staff",
    },
  ];

  export  const productEmployees = [
    {
      id: 1,
      employeeName: "Nguyễn Văn An",
      productName: "Laptop Dell XPS 13",
      productStatus: "Đã đổi giá",
      updatedAt: "2026-05-10 09:30",
    },
    {
      id: 2,
      employeeName: "Trần Thị Bình",
      productName: "iPhone 15 Pro",
      productStatus: "Đã xóa sản phẩm",
      updatedAt: "2026-05-11 10:15",
    },
    {
      id: 3,
      employeeName: "Lê Minh Cường",
      productName: "Tai nghe Sony WH-1000XM5",
      productStatus: "Đã cập nhật tồn kho",
      updatedAt: "2026-05-12 14:20",
    },
    {
      id: 4,
      employeeName: "Phạm Quốc Đạt",
      productName: "Màn hình LG UltraWide",
      productStatus: "Đã chỉnh sửa mô tả",
      updatedAt: "2026-05-13 08:10",
    },
    {
      id: 5,
      employeeName: "Hoàng Gia Hân",
      productName: "Chuột Logitech MX Master 3",
      productStatus: "Đã thêm sản phẩm",
      updatedAt: "2026-05-14 16:45",
    },
    {
      id: 6,
      employeeName: "Đỗ Thành Long",
      productName: "Bàn phím Keychron K8",
      productStatus: "Đã ẩn sản phẩm",
      updatedAt: "2026-05-15 11:00",
    },
    {
      id: 7,
      employeeName: "Vũ Khánh Linh",
      productName: "MacBook Air M3",
      productStatus: "Đã cập nhật ảnh sản phẩm",
      updatedAt: "2026-05-15 13:25",
    },
    {
      id: 8,
      employeeName: "Ngô Thị Mai",
      productName: "Samsung Galaxy S25",
      productStatus: "Đã khôi phục sản phẩm",
      updatedAt: "2026-05-16 09:50",
    },
    {
      id: 9,
      employeeName: "Phan Tuấn Kiệt",
      productName: "iPad Pro 13",
      productStatus: "Đã thay đổi danh mục",
      updatedAt: "2026-05-16 15:40",
    },
    {
      id: 10,
      employeeName: "Nguyễn Hoài Phương",
      productName: "Apple Watch Series 11",
      productStatus: "Đã cập nhật giá khuyến mãi",
      updatedAt: "2026-05-17 17:05",
    },
  ];