export const sizeProduct = ["S","L","Xl","XXL"]
export const colorProduct = ["35","36","37","38"]

export const listProducts = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    img: "https://picsum.photos/200?1",
    quantity: "10",
    price: "1200",
    status: "ACTIVE",
  },
  {
    id: "2",
    name: "Samsung S24",
    img: "https://picsum.photos/200?2",
    quantity: "5",
    price: "1100",
    status: "ACTIVE",
  },
  {
    id: "3",
    name: "MacBook Air M3",
    img: "https://picsum.photos/200?3",
    quantity: "7",
    price: "1500",
    status: "PENDING",
  },
  {
    id: "4",
    name: "Dell XPS 15",
    img: "https://picsum.photos/200?4",
    quantity: "3",
    price: "1800",
    status: "INACTIVE",
  },
  {
    id: "5",
    name: "Logitech G Pro",
    img: "https://picsum.photos/200?5",
    quantity: "20",
    price: "130",
    status: "ACTIVE",
  },
  {
    id: "6",
    name: "Razer BlackWidow",
    img: "https://picsum.photos/200?6",
    quantity: "15",
    price: "170",
    status: "ACTIVE",
  },
  {
    id: "7",
    name: "Sony WH-1000XM5",
    img: "https://picsum.photos/200?7",
    quantity: "8",
    price: "400",
    status: "PENDING",
  },
  {
    id: "8",
    name: "iPad Pro",
    img: "https://picsum.photos/200?8",
    quantity: "12",
    price: "999",
    status: "ACTIVE",
  },
  {
    id: "9",
    name: "Asus ROG Phone",
    img: "https://picsum.photos/200?9",
    quantity: "4",
    price: "1400",
    status: "INACTIVE",
  },
  {
    id: "10",
    name: "AirPods Pro",
    img: "https://picsum.photos/200?10",
    quantity: "25",
    price: "250",
    status: "ACTIVE",
  },
  {
    id: "11",
    name: "Apple Watch",
    img: "https://picsum.photos/200?11",
    quantity: "13",
    price: "500",
    status: "ACTIVE",
  },
  {
    id: "12",
    name: "Lenovo Legion 5",
    img: "https://picsum.photos/200?12",
    quantity: "6",
    price: "1600",
    status: "PENDING",
  },
  {
    id: "13",
    name: "HP Victus",
    img: "https://picsum.photos/200?13",
    quantity: "11",
    price: "1250",
    status: "ACTIVE",
  },
  {
    id: "14",
    name: "MSI Katana",
    img: "https://picsum.photos/200?14",
    quantity: "2",
    price: "1700",
    status: "INACTIVE",
  },
  {
    id: "15",
    name: "Nintendo Switch",
    img: "https://picsum.photos/200?15",
    quantity: "14",
    price: "350",
    status: "ACTIVE",
  },
  {
    id: "16",
    name: "PlayStation 5",
    img: "https://picsum.photos/200?16",
    quantity: "5",
    price: "700",
    status: "PENDING",
  },
  {
    id: "17",
    name: "Xbox Series X",
    img: "https://picsum.photos/200?17",
    quantity: "7",
    price: "650",
    status: "ACTIVE",
  },
  {
    id: "18",
    name: "Canon EOS R50",
    img: "https://picsum.photos/200?18",
    quantity: "3",
    price: "950",
    status: "INACTIVE",
  },
  {
    id: "19",
    name: "DJI Mini 4",
    img: "https://picsum.photos/200?19",
    quantity: "9",
    price: "800",
    status: "ACTIVE",
  },
  {
    id: "20",
    name: "GoPro Hero 12",
    img: "https://picsum.photos/200?20",
    quantity: "16",
    price: "450",
    status: "PENDING",
  },
];